services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
            - vendor:/var/www/vendor
            - node_modules:/var/www/node_modules
        depends_on:
            - db
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: inertia_profile_mu.sql
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: inertia_profile_mu-phpmyadmin
        restart: always
        ports:
            - 8083:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
        depends_on:
            - db
        networks:
            - laravel

volumes:
    dbdata:
    vendor:
    node_modules:

networks:
    laravel:
        driver: bridge
